# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centerWidget = QtWidgets.QVBoxLayout()
        self.centerWidget.setObjectName("centerWidget")
        self.funcLayout = QtWidgets.QHBoxLayout()
        self.funcLayout.setObjectName("funcLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setSpacing(0)
        self.pathLayout.setObjectName("pathLayout")
        self.pathLab = QtWidgets.QLabel(self.centralwidget)
        self.pathLab.setObjectName("pathLab")
        self.pathLayout.addWidget(self.pathLab)
        self.pathLe = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLe.setObjectName("pathLe")
        self.pathLayout.addWidget(self.pathLe)
        self.pathBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pathBtn.setObjectName("pathBtn")
        self.pathLayout.addWidget(self.pathBtn)
        self.pathLayout.setStretch(1, 10)
        self.funcLayout.addLayout(self.pathLayout)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSpacing(0)
        self.searchLayout.setObjectName("searchLayout")
        self.searchLab = QtWidgets.QLabel(self.centralwidget)
        self.searchLab.setObjectName("searchLab")
        self.searchLayout.addWidget(self.searchLab)
        self.searchLe = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLe.setObjectName("searchLe")
        self.searchLayout.addWidget(self.searchLe)
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setObjectName("searchBtn")
        self.searchLayout.addWidget(self.searchBtn)
        self.searchLayout.setStretch(1, 10)
        self.funcLayout.addLayout(self.searchLayout)
        self.funcLayout.setStretch(0, 1)
        self.centerWidget.addLayout(self.funcLayout)
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.treeSplitter = QtWidgets.QSplitter(self.mainSplitter)
        self.treeSplitter.setOrientation(QtCore.Qt.Vertical)
        self.treeSplitter.setObjectName("treeSplitter")
        self.widget = QtWidgets.QWidget(self.treeSplitter)
        self.widget.setObjectName("widget")
        self.localLayout = QtWidgets.QVBoxLayout(self.widget)
        self.localLayout.setContentsMargins(0, 0, 0, 0)
        self.localLayout.setObjectName("localLayout")
        self.localLab = QtWidgets.QLabel(self.widget)
        self.localLab.setObjectName("localLab")
        self.localLayout.addWidget(self.localLab)
        self.localFileTv = QtWidgets.QTreeView(self.widget)
        self.localFileTv.setObjectName("localFileTv")
        self.localLayout.addWidget(self.localFileTv)
        self.widget1 = QtWidgets.QWidget(self.treeSplitter)
        self.widget1.setObjectName("widget1")
        self.remoteLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.remoteLayout.setContentsMargins(0, 0, 0, 0)
        self.remoteLayout.setObjectName("remoteLayout")
        self.remoteLab = QtWidgets.QLabel(self.widget1)
        self.remoteLab.setObjectName("remoteLab")
        self.remoteLayout.addWidget(self.remoteLab)
        self.remoteFileTv = QtWidgets.QTreeView(self.widget1)
        self.remoteFileTv.setObjectName("remoteFileTv")
        self.remoteLayout.addWidget(self.remoteFileTv)
        self.fileTabView = QtWidgets.QTableView(self.mainSplitter)
        self.fileTabView.setObjectName("fileTabView")
        self.centerWidget.addWidget(self.mainSplitter)
        self.horizontalLayout.addLayout(self.centerWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathLab.setText(_translate("MainWindow", "Path:"))
        self.pathBtn.setText(_translate("MainWindow", "Go"))
        self.searchLab.setText(_translate("MainWindow", "Key:"))
        self.searchBtn.setText(_translate("MainWindow", "search"))
        self.localLab.setText(_translate("MainWindow", "local files:"))
        self.remoteLab.setText(_translate("MainWindow", "remote files:"))
