# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(300, 300))
        Login.setMaximumSize(QtCore.QSize(300, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoHzl = QtWidgets.QHBoxLayout()
        self.logoHzl.setObjectName("logoHzl")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.logoHzl.addItem(spacerItem)
        self.logoLab = QtWidgets.QLabel(Login)
        self.logoLab.setEnabled(True)
        self.logoLab.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLab.setObjectName("logoLab")
        self.logoHzl.addWidget(self.logoLab)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.logoHzl.addItem(spacerItem1)
        self.logoHzl.setStretch(1, 1)
        self.verticalLayout.addLayout(self.logoHzl)
        self.signInTipsLab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.signInTipsLab.setFont(font)
        self.signInTipsLab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.signInTipsLab.setAlignment(QtCore.Qt.AlignCenter)
        self.signInTipsLab.setObjectName("signInTipsLab")
        self.verticalLayout.addWidget(self.signInTipsLab)
        self.usernameHzl = QtWidgets.QHBoxLayout()
        self.usernameHzl.setObjectName("usernameHzl")
        self.usernameLab = QtWidgets.QLabel(Login)
        self.usernameLab.setObjectName("usernameLab")
        self.usernameHzl.addWidget(self.usernameLab)
        self.verticalLayout.addLayout(self.usernameHzl)
        self.usernameLe = QtWidgets.QLineEdit(Login)
        self.usernameLe.setText("")
        self.usernameLe.setObjectName("usernameLe")
        self.verticalLayout.addWidget(self.usernameLe)
        self.passwordHzl = QtWidgets.QHBoxLayout()
        self.passwordHzl.setObjectName("passwordHzl")
        self.pwdLab = QtWidgets.QLabel(Login)
        self.pwdLab.setObjectName("pwdLab")
        self.passwordHzl.addWidget(self.pwdLab)
        self.pwdFgtLab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pwdFgtLab.setFont(font)
        self.pwdFgtLab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwdFgtLab.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.pwdFgtLab.setObjectName("pwdFgtLab")
        self.passwordHzl.addWidget(self.pwdFgtLab)
        self.verticalLayout.addLayout(self.passwordHzl)
        self.pwdLe = QtWidgets.QLineEdit(Login)
        self.pwdLe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLe.setObjectName("pwdLe")
        self.verticalLayout.addWidget(self.pwdLe)
        self.signInBtn = QtWidgets.QPushButton(Login)
        self.signInBtn.setObjectName("signInBtn")
        self.verticalLayout.addWidget(self.signInBtn)
        self.newAccLab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.newAccLab.setFont(font)
        self.newAccLab.setScaledContents(True)
        self.newAccLab.setAlignment(QtCore.Qt.AlignCenter)
        self.newAccLab.setOpenExternalLinks(True)
        self.newAccLab.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.newAccLab.setObjectName("newAccLab")
        self.verticalLayout.addWidget(self.newAccLab)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.logoLab.setText(_translate("Login", "logo"))
        self.signInTipsLab.setText(_translate("Login", "Sign in for distribute disks"))
        self.usernameLab.setText(_translate("Login", "Username:"))
        self.pwdLab.setText(_translate("Login", "Password:"))
        self.pwdFgtLab.setText(_translate("Login", "Forgot password?"))
        self.signInBtn.setText(_translate("Login", "Sign in"))
        self.newAccLab.setText(_translate("Login", "New user? create an account"))
