CLNT_NAME = "hp"
CLNT_ID = 1
HW_HOST = "www.huiwanit.cn"
HW_PORT = 9001

HW_DATA_TYPE_LOGIN = 0
HW_DATA_TYPE_CMD = 1
HW_DATA_TYPE_BINARY = 2

HW_DATA_TYPE = (HW_DATA_TYPE_LOGIN, HW_DATA_TYPE_CMD, HW_DATA_TYPE_BINARY)

